Create Exercises_7_a_b_c.cpp
oreillymedia/Learning-OpenCV-3_examples pull request #32
Opened 2017-06-15 01:37 UTC by jsxyhelu

Execrcises a,b,c of Chapter 7. Functors in OpenCV ,without Exercise d

2017-06-15 01:41 UTC, jsxyhelu commented
in my oppinion,Exercise d may be hard to translate into code

2017-06-15 03:02 UTC, garybradski requested changes
Made some requested changes. Thanks for doing these. I'm just trying to keep everything consistent (and will do it to all the files). See the comments

2017-06-15 03:02 UTC, garybradski commented on Exercises_7_a_b_c.cpp
> +#include "stdafx.h"
stdafx.h is particular to windows (pre-compiled headers for speed), best not to include it for everyone.

2017-06-15 03:02 UTC, garybradski commented on Exercises_7_a_b_c.cpp
> +
I like comments at the top of every file that tell what it is:
// Answers to exercise 7(a)(b) and (c)

2017-06-15 03:02 UTC, garybradski commented on Exercises_7_a_b_c.cpp
> +
In all files, I want the program to say what it is:
void help(const char **argv) {
  cout << "\n\n"
       << "Exercises 7a-c:\n"
       << "Call:\n" << argv[0]
       << endl;
}

2017-06-15 03:02 UTC, garybradski commented on Exercises_7_a_b_c.cpp
> +	/************************************************************************/
See above, add in a call:
help(argv);

2017-06-16 11:21 UTC, jsxyhelu commented on Exercises_7_a_b_c.cpp
> +#include "stdafx.h"
OK，i get it.

2017-06-16 12:53 UTC, jsxyhelu commented on Exercises_7_a_b_c.cpp
> +
in my opinion,exercise 7 does not need something like argv.
Can I omit this item?
just in exercise 7,of course.

2017-06-16 12:59 UTC, jsxyhelu reviewed
Exercises at end of Chapter 7,I add the execise 4.
I solved the first half of the problem on paper, but I didn't know how to pass it up

2017-06-16 23:50 UTC, garybradski commented on Exercises_7_a_b_c.cpp
> +
That's fine, it's just a standard template that I'm using

2017-06-17 00:22 UTC, jsxyhelu commented on Exercises_7_a_b_c.cpp
> +
ok,what should i do to make  these code  be merged?

2017-06-17 07:13 UTC, closed without merging